### ISSUE TITLE
Issue in an example at zetcode.com 

### ISSUE THREAD

**Issue by luchoman08** [janbodnar/Python-Skolenie-Web#1]
I write here because are no more communication Chanel with zetcode admin (I guess it is you)

At this [link](https://zetcode.com/golang/csv/) some examples does not handle correctly the error, like 

```go

package main

import (
    "encoding/csv"
    "fmt"
    "io"
    "log"
    "os"
)

func main() {

    f, err := os.Open("numbers.csv")

    if err != nil {

        log.Fatal(err)
    }

    r := csv.NewReader(f)
    for {

        record, err := r.Read()
        if err == io.EOF {
            break
        }

       // here you need to review the error
       if err != nil {
            return log.Fatal(err)
       }

        for value := range record {
            fmt.Printf("%s\n", record[value])
        }
    }
}
```
that happens in at least two examples at the page

**Comment by janbodnar** [comment]
Thanks for the feedback. I have found one example, which I have corrected. 

(The contact email is at the bottom of each page.)
